name: build-and-publish
on: 
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: Build Fanbox Web
        run: cd cmd/web && CGO_ENABLED=0 go build -o build/web

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp-etin.alwaysdata.net
          username: etin_fanbox
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./cmd/web/build/
          server-dir: ./fanbox.space/
