name: build-and-publish
on: 
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Build static assets
        run: cd ui && npm run build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: Build Fanbox Web
        run: cd cmd/web && CGO_ENABLED=0 go build -o build/web

      - name: Deploy via SSH
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ssh-etin.alwaysdata.net
          remote-user: etin_fanbox
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./cmd/web/build/
          destination-path: ./fanbox.space/
          rsync-options: --chmod=+X
